/*
 * generated by Xtext
 */
package org.efaps.eql.validation;

import org.eclipse.xtext.validation.Check;
import org.efaps.eql.eQL.Comparison;
import org.efaps.eql.eQL.EQLPackage;
import org.efaps.eql.eQL.OneWhere;

/**
 * Custom validation rules.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class EQLJavaValidator
    extends org.efaps.eql.validation.AbstractEQLJavaValidator
{

    @Check
    public void inMustNotBeEmpty(final OneWhere _oneWhere)
    {
        if (Comparison.IN.equals(_oneWhere.getComparison())) {
            error("In must not be empty", EQLPackage.Literals.ONE_WHERE__VALUES, "E001", _oneWhere.getAttribute());
        }
    }
}
