/*
 * generated by Xtext
 */
package org.efaps.eql;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EQLRuntimeModule extends org.efaps.eql.AbstractEQLRuntimeModule {

}
