/*
* generated by Xtext
*/
package org.efaps.eql;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EQLStandaloneSetup extends EQLStandaloneSetupGenerated{

	public static void doSetup() {
		new EQLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

